### ISSUE TITLE
How do I keep the ESDF map after a flight?

### ISSUE THREAD

**Issue by GanAHE** [HKUST-Aerial-Robotics/Fast-Planner#101]
In the demo, I noticed that your project was able to preserve the map after the flight, but I couldn't find a way to implement it in the 
 code, how did you do it?

**Comment by infinity0323** [comment]
Hello! I have the same quesiton as you. How did you solve it?

**Comment by Long-Wu-code** [comment]
I get same question? Could you give me some suggestions?
