### ISSUE TITLE
Frequent aggresive wrong motion of quadrotor

### ISSUE THREAD

**Issue by SwiftGust** [HKUST-Aerial-Robotics/Fast-Planner#12]
Hi.
First of all thank you for sharing great work!

I found an issue during the simulation.
That it is often observed that quadrotor model follows trajectory undesirable way
that the vehicle flip towards wrong direction then return & starts to follow trajectory (See GIF below)

This easily can be observed especially when transitioning from stopped state(WAIT_TARGET) to executing new trajectory(EXEC_TRAJ) or rarely seen while following trajectory.

I'd like to know why and is this can easily be solved?

Thanks in advance.

P.S. Launch file & parameters are left untouched.
![Peek 2020-01-15 19-53](https://user-images.githubusercontent.com/13569579/72507011-6802ab80-3886-11ea-99a2-9bae9cd5a39d.gif)

**Comment by ZbyLGsc** [comment]
@SwiftGust The reason is that currently the planner does not plan the trajectory for heading (yaw angle), but just naively control the drone to head toward the direction of velocity. Therefore, if you select a goal behind the drone, it will aggressively turn back.

**Comment by ZbyLGsc** [comment]
@SwiftGust The previous code does not have such a problem, because we have omnidirectional perception and we make the heading a fixed value. So we did not have the aggressive turn issue. But currently to simulate a camera with limited FoV, we should change the heading. I am writing a simple heading planner, and I will release it in a few days. This problem can be solved then.

**Comment by ZbyLGsc** [comment]
@SwiftGust The heading planner is now released to enable smoother change of heading direction. It should solve the problem of aggressive wrong motion you found. You can test it and close this issue if no problem exists.

**Comment by SwiftGust** [comment]
@ZbyLGsc Hi, Thank you for the update.
I have tested this and the vehicle smoothly follows B-spline trajectory any motion well.
Great work!
