### ISSUE TITLE
Can't install libarmadillo-dev 

### ISSUE THREAD

**Issue by wbzhang233** [HKUST-Aerial-Robotics/Fast-Planner#15]
I'm sorry to bother you but I can't solve this issue by myself.I can't install libarmadillo-dev but I have installed libarmadillo6.I try `sudo apt install -f` but it failed.

```
[sudo] wbzhang233 的密码： 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
没有可用的软件包 libarmadillo-dev，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

E: 软件包 libarmadillo-dev 没有可安装候选
```

**Comment by ZbyLGsc** [comment]
Let me google it for you. You may try: https://zoomadmin.com/HowToInstall/UbuntuPackage/libarmadillo-dev
