### ISSUE TITLE
How to apply this algorithm to UAV

### ISSUE THREAD

**Issue by Xchegg** [HKUST-Aerial-Robotics/Fast-Planner#163]
When using an unmanned vehicle, due to the low camera position, the algorithm recognizes the vehicle as an obstacle. How to adjust the parameters in  kino algorithm. xml  to prevent the vehicle from being recognized as an obstacle?
Additionally, the perspective of the map seen on Rviz is from the bottom up. How can this issue be resolved?

**Comment by zsssyzx** [comment]
Is it resolved now?

**Comment by Xchegg** [comment]
> Is it resolved now?

It has been resolved. Simply converting the coordinate system of the depth camera will solve the issue.
