### ISSUE TITLE
dyn_planner node issue

### ISSUE THREAD

**Issue by michaelchi08** [HKUST-Aerial-Robotics/Fast-Planner#2]
Hello,

Just reporting this error. The code is running though. 

dyn_planner_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 36; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
Stack trace (most recent call last):
#8    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#7    Object "/home/michael/catkin_ws/devel/lib/plan_manage/dyn_planner_node", at 0x412978, in _start
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff76ad3d82f, in __libc_start_main
#5    Object "/home/michael/catkin_ws/devel/lib/plan_manage/dyn_planner_node", at 0x41248f, in main
#4    Object "/home/michael/catkin_ws/devel/lib/plan_manage/dyn_planner_node", at 0x42055e, in dyn_planner::PlanningFSM::init(ros::NodeHandle&)
#3    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff76ad4ac81, in __assert_fail
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff76ad4abd6, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff76ad54029, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff76ad52428, in gsignal
Aborted (Signal sent by tkill() 27357 1000)
[ WARN] [1563280908.273078848]: Finished generate random map 
[dyn_planner_node-1] process has died [pid 27357, exit code -6, cmd /home/michael/catkin_ws/devel/lib/plan_manage/dyn_planner_node /laser_cloud_surround:=/random_forest/all_map /odom_world:=/state_ukf/odom __name:=dyn_planner_node __log:=/home/michael/.ros/log/bdfb3aa8-a7c6-11e9-8a55-f894c28abe6b/dyn_planner_node-1.log].
log file: /home/michael/.ros/log/bdfb3aa8-a7c6-11e9-8a55-f894c28abe6b/dyn_planner_node-1*.log
[ WARN] [1563280944.450820443]: [waypoint_generator] invalid goal in manual-lonely-waypoint mode.
[ WARN] [1563281031.431866653]: [waypoint_generator] invalid goal in manual-lonely-waypoint mode.
[ WARN] [1563281075.151515836]: [waypoint_generator] invalid goal in manual-lonely-waypoint mode.
[ WARN] [1563281085.073110464]: [waypoint_generator] invalid goal in manual-lonely-waypoint mode.

**Comment by ZbyLGsc** [comment]
@michaelchi08 you did not set a valid goal using the 3D nav tool. The most possible reason is that the z value was negative.
