### ISSUE TITLE
Question in topo_prm.cpp -> function <<needConnection>>

### ISSUE THREAD

**Issue by MichaelFYang** [HKUST-Aerial-Robotics/Fast-Planner#26]
In the function "needConnection", if the checking for a shorter path is true, should the neighbor for both Graph node g1 and g2 need to be changed. 
[OLD]
if (pathLength(path1) < pathLength(path2)) {
            g1->neighbors_[i]->pos_ = pt;
            // ROS_WARN("shorter!");
}
---->
[NEW]
if (pathLength(path1) < pathLength(path2)) {
            g1->neighbors_[i]->pos_ = pt;
            g2->neighbors_[j]->pos_ = pt;
            // ROS_WARN("shorter!");
}
Or maybe I miss understanding some parts of code.

**Comment by ZbyLGsc** [comment]
@MichaelFYang Yes you are right. 
But since the we already have: 'g1->neighbors_[i]->id_ == g2->neighbors_[j]->id_',
so the two pointers of neighbors point to the same node, and we only need to change the 'pos' of the node once.
Therefore the original code is also correct.

**Comment by ZbyLGsc** [comment]
Please close this issue given no other problem

**Comment by MichaelFYang** [comment]
I see. Thanks.
