### ISSUE TITLE
Usage with Flight Controllers

### ISSUE THREAD

**Issue by mzahana** [HKUST-Aerial-Robotics/Fast-Planner#27]
Hi @ZbyLGsc ,

I would like to test planners in this project with an actual flight controller. What are the control commands (i.e. position/velocity/acceleration) that are sent to the flight controller?

Thanks.

**Comment by mzahana** [comment]
I found that `/planning/pos_cmd` topic has the reference commands. I assume that this what goes to the flight controller, right?

**Comment by ZbyLGsc** [comment]
Correct. The controller is implemented in uav_simulator/so3_control. @mzahana

**Comment by mzahana** [comment]
Thanks!
