### ISSUE TITLE
Changing target pose on the way

### ISSUE THREAD

**Issue by mzahana** [HKUST-Aerial-Robotics/Fast-Planner#31]
Hi @ZbyLGsc 
When I try to publish a new goal waypoint to `/move_base_simple/goal`  while the drone is already on its way to a previous one, it does not change its trajectory to the new one and just continues to complete flying to the current goal. Is there a way to make the drone abort the current goal and change to the new one?

**Comment by ZbyLGsc** [comment]
Yes, use the kino_replan directly, or modify the FSM of topo_replan. @mzahana
