### ISSUE TITLE
thread safety issues about map updatig

### ISSUE THREAD

**Issue by WangChanglong17** [HKUST-Aerial-Robotics/Fast-Planner#32]
hello, I see that in map update thread , data was written to distance buffer.  In other thread, data in distance was read. Does this exist thread safety issues?

**Comment by ZbyLGsc** [comment]
@WangChanglong17 There is no Multi-threaded Spinning in our code, therefore the planning and mapping are conducted in the same thread. You can easily validate what I claim by outputting something in the callbacks of mapping.

**Comment by ZbyLGsc** [comment]
FYI, http://wiki.ros.org/roscpp/Overview/Callbacks%20and%20Spinning
