### ISSUE TITLE
Obstacle inflation to account for different drone sizes

### ISSUE THREAD

**Issue by mzahana** [HKUST-Aerial-Robotics/Fast-Planner#33]
Hi @ZbyLGsc 

How to change obstacle inflation to account for different drone sizes?
Is it [this one](https://github.com/HKUST-Aerial-Robotics/Fast-Planner/blob/master/fast_planner/plan_manage/launch/topo_algorithm.xml#L61)

**Comment by ZbyLGsc** [comment]
@mzahana As you already called it, there is a parameter named obstacles_inflation in the .xml file.
