### ISSUE TITLE
Kino Planner  Strange Paths

### ISSUE THREAD

**Issue by lgh5054** [HKUST-Aerial-Robotics/Fast-Planner#37]
![test-2020-07-20_17 05 49](https://user-images.githubusercontent.com/35057391/87924913-7f7f5300-caba-11ea-909a-0ffdd2279cb7.gif)

Hello, I'm testing Kino planner through gazebo. 

The kino planner indicates a strange path even though there are no obstacles in the way

What's the problem?

And the YAW axis rotation speed of the drone is too fast. Can you reduce it?

**Comment by skyaid** [comment]
@ZbyLGsc Thank you for your answer. It's working fine.

Can I change the size of the OCTOMAP block for an obstacle?

**Comment by ZbyLGsc** [comment]
There is no OctoMap in this project. 
You can change the voxel size by 'sdf_map/resolution'.
@skyaid
