### ISSUE TITLE
perhaps there are two mistakes in the 5th formular in the paper

### ISSUE THREAD

**Issue by tiemuhua** [HKUST-Aerial-Robotics/Fast-Planner#46]
the 5th formular in the paper perhaps should be this one
![image](https://user-images.githubusercontent.com/46767782/91003387-ba1d6380-e603-11ea-80ab-be4e4dedccc8.png)

but in the paper it look like this
![image](https://user-images.githubusercontent.com/46767782/91003435-e0db9a00-e603-11ea-9a49-5978927bfc79.png)

**Comment by ZbyLGsc** [comment]
@tiemuhua Yes you are right. Actually we have already found the problem, but unfortunately there is no way to correct it after publication. Thanks for your reminder.
