### ISSUE TITLE
it seems like there are two function in edu_envirment.cpp with return value missed

### ISSUE THREAD

**Issue by tiemuhua** [HKUST-Aerial-Robotics/Fast-Planner#47]
pair<double, Eigen::Vector3d> EDTEnvironment::interpolateTrilinear(double values[2][2][2],......)in line 59
and
pair<double, Eigen::Vector3d> EDTEnvironment::evaluateEDTWithGrad(const Eigen::Vector3d& pos,...,...)in line 82

it seems like these function do not return any thing
![image](https://user-images.githubusercontent.com/46767782/91192427-7ff9b200-e728-11ea-9cac-93582503ae11.png)

by the way, what does the abbreviate EDT means?
i only find Euclid Distance Field in the paper, but nothing with the abbreviate EDT.

**Comment by ZbyLGsc** [comment]
@tiemuhua The results are assigned to 'value' and 'grad'. The function should have been declared to return 'void' type instead of 'pair<>'. EDT refers to Euclidean distance transform.
