### ISSUE TITLE
Where is heading_planner?

### ISSUE THREAD

**Issue by dssdyx** [HKUST-Aerial-Robotics/Fast-Planner#50]
I see there is a series of parameters named "heading_planner" in topo_algorithm.xml. But I can not change them to reduce the yaw rate and find where they are in codes. Could you tell me what these parameters mean ?

**Comment by ZbyLGsc** [comment]
These parameters are not used in the current planner but will be used in a future release. Currently the yaw is controlled to face toward the flight direction (or name it velocity tracing yaw). If you want to reduce the yaw rate, try reduce parameter: "optimization/lambda7". This will relax the velocity tracking constraint and enable higher smoothness.

The code for yaw planning is in "void FastPlannerManager::planYaw(const Eigen::Vector3d& start_yaw)".

**Comment by dssdyx** [comment]
@ZbyLGsc Thank you for your answer!
