### ISSUE TITLE
Is there other method to increase the distance between planned paths and obstacles?

### ISSUE THREAD

**Issue by dssdyx** [HKUST-Aerial-Robotics/Fast-Planner#51]
In topo-planner, I know "obstacles_inflation" can make paths further than obstacles. But this way will burden processor. From paper, the base of B-spline paths is topo-graph. Is there any way to increase the distance between planned paths and obstacles, particularly in the situation of single obstacle?

**Comment by ZbyLGsc** [comment]
You can increase "optimization/dist0", which improves the clearance of B-spline.

**Comment by dssdyx** [comment]
@ZbyLGsc Thanks for your advice！ It's very useful!
