### ISSUE TITLE
Some questions about using fast planner with quad copter in SITL

### ISSUE THREAD

**Issue by haolong12321** [HKUST-Aerial-Robotics/Fast-Planner#53]
hello,
First of all, I wanted to say great work with the repo and papers!

I'm testing the kino algorithm with Gazebo SITL and having some issues.
I uploaded a video taken from rviz : https://streamable.com/rb17d1
The  red arrow is the odometry from the quad copter in Gazebo vs. the planned traj of the planner.
There is a noticeable "overshooting" of the drone trajectory, that may possibly lead to failures in avoiding obstacles. 
I've configured the drone's FCU (we use arducopter) to be as "fast" as it can be (in roll, pitch, yaw), however the generated trajectories are still not feasbile for the drone.
When I decrease the max_acc and max_vel parameter in the launch file it's gets a bit better but the drone is still unable to perform the exact traj (especially the yaw rate).
could you help me try to optimize the planned path to fit to my drone's performance? Is there something I'm missing?

**Comment by ZbyLGsc** [comment]
What you describe is not a problem of the planner, it is a control problem, i.e., the real pose can not catch up with the desired pose. Given a good trajectory tracking controller, such as the one used in our simulator, the drone should be able to follow the trajectory well, therefore I suggest you to check the controller used in Gazebo.
