### ISSUE TITLE
很抱歉又开了个issue

### ISSUE THREAD

**Issue by tiemuhua** [HKUST-Aerial-Robotics/Fast-Planner#55]
周学长，我现在在西交自动化，刚上大三。这个暑假认真研究了fast-planner的代码，学长的讲解令我受益匪浅。请问寒假以及明年暑假有没有机会去港科大交流。另外，能不能加一下您的微信或者邮箱（没在学长的主页和博客上找到邮箱地址）。

**Comment by ZbyLGsc** [comment]
主页上再找找？:laughing:
