### ISSUE TITLE
Global map using fast-planner

### ISSUE THREAD

**Issue by guo253** [HKUST-Aerial-Robotics/Fast-Planner#60]
Hi,
The first pic in readme.md is a global map. Does it be created using fast-planner?
I comment line 652-722 in sdf_map.cpp as said in another issue,but no change in the demo.
Wish your help,thanks.

What is the difference between the the global map using fast-planner and fiesta?

**Comment by ZbyLGsc** [comment]
The difference between global and local is that: in global map, we do not remove any data in map update. In contrast, for local map, data that is not within a cube centered at the UAV will be removed, or in other word, information far from the UAV is removed.
If you see no effect, it might be visualization problem (only a local area is published).
