### ISSUE TITLE
Can we get the direction of the obstacle relative to the aircraft from  the ESDF map?

### ISSUE THREAD

**Issue by IngaVS** [HKUST-Aerial-Robotics/Fast-Planner#61]
UAV can't find path when UAV in the margin of obstacle,but the obstacle is behind the UAV. So I don't want  to consider the obstacle  behind the UAV when search path

**Comment by ZbyLGsc** [comment]
You can query the ESDF and get the gradient.

**Comment by IngaVS** [comment]
Thank you.
I set the margin = 0.5m before , it's too large.  The airplane will in the margin sometimes, and  can't find path because the noisy will be enlarged to a bolus(r=0.5m). But if margin = 0.2m or 0.3m, the occupancy map need  high accuracy, because length of the airplane is 0.6m.
