### ISSUE TITLE
some questions about  trajectory tracking controller

### ISSUE THREAD

**Issue by 958117216** [HKUST-Aerial-Robotics/Fast-Planner#63]
Now I am using the fast_planner which is very amazing,but  there are some questions in tracking the trajectory which is produced by the fast_planner.So I just want to ask whether there are some papers about good trajectory tracking controllers, such as the one used in your simulator?

**Comment by ZbyLGsc** [comment]
Geometric tracking control of a quadrotor uav on se (3),” in Proc. of the IEEE Control and Decision Conf. (CDC)

**Comment by 958117216** [comment]
Thank you!
