### ISSUE TITLE
Clarifications regarding plan_env

### ISSUE THREAD

**Issue by FaboNo** [HKUST-Aerial-Robotics/Fast-Planner#67]
I am looking at sdf_map.cpp and I have few questions

1. Concerning the topic `/sdf_map/occupancy` which is advertising pointCloud2, from what I can see the point cloud are related to the inflated map already - see screenshot below in which  I superimposed the depth map and the "occupancy map" 
![occupancy](https://user-images.githubusercontent.com/31440972/98004021-b706d680-1def-11eb-8c97-9b58227edbe2.png)

2. So what is the difference between `/sdf_map/occupancy` and `/sdf_map/occupancy_inflate`? The only difference I can see is the parameter `local_map_margin` which is divided by 2 in one case. Is it related to the fact that you can display a map in a greater area with `/sdf_map/occupancy_inflate`? Besides what is the meaning of  `local_map_margin`?

3. The parameter `obstacle_inflation` should be at least equal the radius of the circle centered on the drone? Am I right because in the simulation this parameter is really small (0.09).

4.I am a bit confused about md_.local_bound_min_ and md_.local_bound_max_. I can see that they contain the indices of the position of the (min, max) of a cube but how is it related to the position of the drone? 

Thanks you for your support and for this amazing piece of work

**Comment by ZbyLGsc** [comment]
occupancy map inflated by "obstacle_inflation" produces occupancy_inflate.
local_bound_min_/max_ are related to the updated regions of each frame.
