### ISSUE TITLE
Sending the UAV to multiple points without using 2D Nav Goal on rviz

### ISSUE THREAD

**Issue by bharat787** [HKUST-Aerial-Robotics/Fast-Planner#68]
I'm trying to make the UAV go on a set path. I changed the flight_type to 2 in kino_replan.launch to use and set the preset points in  kino_alogorithm.xml and kino_replan.launch.
But during execution I still have to use the 2D Nav Goal button in rviz to make the UAV navigate to the next preset point.

Is there a way to make it automatically go through all the set points.

Thanks

**Comment by ZbyLGsc** [comment]
preset multiple points are not supported for kino_replan; use topo_replan instead.
Thanks for reporting the problem, I will correct the comment in launch file soon.

**Comment by ZbyLGsc** [comment]
If you are determined to use kino-replan, then you should modify the state machine(KinoReplanFSM) to enable continuous execution of the waypoints without using 2D Nav Goal to trigger it repeatedly.

**Comment by bharat787** [comment]
Thanks for the suggestion i'll try them out

**Comment by bharat787** [comment]
> Presetting multiple points is not supported for kino_replan, the waypoints will be executed one by one;
> Use topo_replan instead in which you only need to trigger the planner once.

Facing the same issue on topo_replan.

**Comment by ZbyLGsc** [comment]
Did you set flight_type=3 and set point_num and point0, point1 ... pointn properly?

**Comment by bharat787** [comment]
> Did you set flight_type=3 and set point_num and point0, point1 ... pointn properly?

![Screenshot from 2020-11-07 08-40-56](https://user-images.githubusercontent.com/40318290/98430730-95e70400-20d5-11eb-886c-71537f9731af.png)

The comments did not mention there was a mode 3, but it works now!

Thanks for the fast responses.
