### ISSUE TITLE
drone flying through obstacles

### ISSUE THREAD

**Issue by vanshilshah97** [HKUST-Aerial-Robotics/Fast-Planner#69]
Our occupancy map is proper and shows points where the obstacle is, but when we are giving waypoints, the planned trajectory passes through obstacles and the drone collides with the obstacle.

Any idea regarding this anomaly 
A humble request to reply whenever convenient due to the time-sensitive nature of the project

**Comment by ZbyLGsc** [comment]
I can not reproduce the problem, pls show more details.

**Comment by buenos-dan** [comment]
@vanshilshah97 I meet the same problem, have you found a solution?

**Comment by iamrajee** [comment]
We are also facing a similar issue in SITL while trying out [beomsu7's](https://github.com/beomsu7/Fast-Planner) fork. Any resolution?
https://user-images.githubusercontent.com/25712145/172568365-0666c820-42fd-4b14-9fa5-bbdccc1a3d8c.mp4
