### ISSUE TITLE
Unable to change height

### ISSUE THREAD

**Issue by Stavya1993** [HKUST-Aerial-Robotics/Fast-Planner#71]
Using the kino_replan, I am using the /move_base_simple/goal to move the drone. Whenever, I change only the height of the system, the kino_replan fails to find trajectory. Additionally, it doesnt seem to change the height when x and y are also changed. I have changed the virtual cieling height to 10 in the kino_algorithm.launch file.

**Comment by ZbyLGsc** [comment]
1. /move_base_simple/goal will set the height to a fixed value by default, since it is not convenient to specify the height with it.
2. There is a known issue: when the target x,y position is identical to the current x,y position the planner may not find paths.

**Comment by ZbyLGsc** [comment]
Currently one can only specify the target height by the preset waypoints in the launch file.

**Comment by Stavya1993** [comment]
Thanks. This makes sense!
