### ISSUE TITLE
lack of files for header

### ISSUE THREAD

**Issue by gcc18** [HKUST-Aerial-Robotics/Fast-Planner#75]
Some header are not exist  so the project can not be compiled correctly

> 
fatal error: multi_map_server/MultiOccupancyGrid.h: No such file or directory
 #include <multi_map_server/MultiOccupancyGrid.h>
> 

> 
fatal error: plan_manage/Bspline.h: No such file or directory
 #include <plan_manage/Bspline.h>
>

**Comment by mehhdiii** [comment]
Did the issue resolve? I seem to be having the same issue. I am on Ubuntu 18.04 (ROS melodic)

**Comment by Tiga002** [comment]
@mehhdiii  @eliabntt  
BSpline.h is the header file for including the custom message type in msg/BSpline.msg

**Comment by doche** [comment]
Did the issue resolve? I seem to be having the same issue. I am on Ubuntu 18.04 (ROS melodic),pls help!

**Comment by doche** [comment]
> @mehhdiii @eliabntt BSpline.h is the header file for including the custom message type in msg/BSpline.msg

so? how to solve it? thanks
