### ISSUE TITLE
 UAV to multiple points error

### ISSUE THREAD

**Issue by lgh5054** [HKUST-Aerial-Robotics/Fast-Planner#78]
I set 
map size x : 100
                y : 80
                z:  5
flight_type=3 and set point_num and point0, point1

However, Waypoint does not work after 40m 

Is there anything I need to set aside?

**Comment by lgh5054** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35057391/99619362-a5b40000-2a66-11eb-9032-b95652527b4c.gif)

[ERROR] [1605757813.401638370]: max vel: 19.993457, max acc: 62.215169

**Comment by ZbyLGsc** [comment]
@lgh5054 After some checks we find the issue is caused by bad time reallocation. The problem is already fixed and feel free to report if you still find other problems.
