### ISSUE TITLE
Getting all positions, velocities and yaw angless in predicted trajectory

### ISSUE THREAD

**Issue by LiJing9876** [HKUST-Aerial-Robotics/Fast-Planner#89]
Hey,

I'm using kino_replan and I'm trying to get future position, velocities and yaw angles of the predicted bspline.
I went through all the topics that the planner is publishing and found only "/planning/bspline" and "/planning_vis/trajectory" which have the future positions (I wasn't able to determine what the exact different between them).

Is there any way to add the predicted velocities and yaw angles to one of these topics or maybe create new topic containing them?

Additionally, is there any way to get the predicted time of each point in the predicted trajectory?

Thanks Ahead!

**Comment by ZbyLGsc** [comment]
Pls check traj_server about how the commands are published and you will find out the info you need.
