### ISSUE TITLE
pcl_render_node/depth is empty

### ISSUE THREAD

**Issue by limit944** [HKUST-Aerial-Robotics/Fast-Planner#91]
@ZbyLGsc Hello Dr. Zhou, I meet some questions when I run the simulator.In the kino_replan.launch, you comment that don't set cloud_topic if I want to use depth_topic and camera_pose_topic.But  the topic pcl_render_node/depth didn't exist data, whatever commenting out  `<remap from="/sdf_map/cloud" to="$(arg cloud_topic)"/>`
in the kino_algorithm.xml.And the robot can't replan the trajectory in depth image method.Is my operation wrong? And is the CUDA necessary for depth image?Thank!

**Comment by surfii3z** [comment]
I also have this problem before, it's probably due to wrong gencode when building with CUDA
